language: node_js
group: dev

node_js:
- '12.3.1'

os:
- linux

sudo: required
dist: xenial

# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
#       key_url: 'https://dl.winehq.org/wine-builds/Release.key'
#     packages:
#     - winehq-staging
#     - build-essential
#     - gcc-multilib
#     - g++-multilib
#     - libstdc++6

branches:
  only:
  - master

before_install: # redundant, because travis does not use addons for xenial Apr 2018
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- wget -nc https://dl.winehq.org/wine-builds/Release.key ; sudo apt-key add Release.key ; sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
- sudo apt-get update -q
- sudo apt-get install winehq-staging build-essential libstdc++6 gcc-multilib g++-multilib -y --allow-unauthenticated

install:
- npm install -g electron-builder
- npm install

script:
- /sbin/ldconfig -p | grep stdc++ ; apt list gcc* ; strings /usr/lib*/libstdc++.so.6 | grep LIBCXX ; strings /usr/lib/*/libstdc++.so.6 | grep LIBCXX
- npm run-script build

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "dist/*.exe"
    skip_cleanup: true
    on:
      branch: master
            
cache:
  directories:
    - node_modules