language: node_js

node_js:
- '10.0.0'

os:
- linux

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'
      key_url: 'https://dl.winehq.org/wine-builds/Release.key'
    packages:
    - winehq-staging
    - build-essential
    - gcc-multilib
    - g++-multilib
    - libstdc++6

branches:
  only:
  - master

install:
- npm install -g electron-builder
- npm install

script:
- /sbin/ldconfig -p | grep stdc++ ; apt list gcc* ; strings /usr/lib*/libstdc++.so.6 | grep LIBCXX ; strings /usr/lib/*/libstdc++.so.6 | grep LIBCXX
- npm run-script build

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "dist/*.exe"
    skip_cleanup: true
    on:
      branch: master
            
cache:
  directories:
    - node_modules